### ISSUE TITLE
Keresőben ne számítson ékezet, whitespace, vesszők, stb, csak a szöveg

### ISSUE THREAD

**Issue by RedyAu** [reformatus/enekeskonyv-app#18]

**Comment by boobaa** [comment]
Magyarul a keresőkifejezésként beírt összes szó tetszőleges sorrendben, egymástól tetszőleges távolságra, akár szórészletként legyen benne a talált versszak szövegében? Azaz „hitlen aki” jelenítse meg találatként az 1,1-et?

**Comment by RedyAu** [comment]
Nem, ennyire nem kell szerintem se absztrahálni. A sorrend számítson, de akár egy kihagyott szó ne, ha lehet ilyet csinálni. A lényeg viszont, hogy az ékezetek, a feles whitespace és a vesszők legyenek kiszűrve :D
