### ISSUE TITLE
Hibajelentés

### ISSUE THREAD

**Issue by RedyAu** [reformatus/enekeskonyv-app#20]
Külön app-bug és énekhiba jelentési lehetőség az appból.
Kikészített GitHub Issue Templatekre ugorhat böngészőben (igaz GitHub fiók kell hozzá, de legalább nem fogunk annyit kapni 😅).
Ha a GitHub fiók nagyon limitáló, lehet Google Forms is.

**Comment by boobaa** [comment]
Első körben az is elég lehet, ha az áruház(ak)ban (is) közzétett email-címekre küld emailt. IIRC ahhoz még külön permission se kell, hiszen megnyitja a telefonokon amúgy is elérhető levelezőprogramot.

**Comment by RedyAu** [comment]
Ez igaz, email templatet is tud átadni. Androidon legalábbis biztos, de szerintem a sima mailto:-t iOS is kell, hogy támogassa.

**Comment by boobaa** [comment]
closed by #42
