### ISSUE TITLE
Link megnyitás off by one error

### ISSUE THREAD

**Issue by RedyAu** [reformatus/enekeskonyv-app#52]
Énekek utolsó versszaka invalidnak van értékelve

**Comment by boobaa** [comment]
Hogyan kell ezt reprodukálni? …mert ugye a 48-as könyvben a versszakok számozásában vannak lukak (mint ahogy a 21-es könyvben az énekek számozásában).

**Comment by RedyAu** [comment]
Bármelyik ének utolsó versszakát ha megpróbálod megosztani (közvetlenül vagy listában), a verseId validátor visszadobja beolvasáskor.

**Comment by RedyAu** [comment]
Más volt a bug, de javítva
