### ISSUE TITLE
68. zsoltár 17. versszaka hiányos

### ISSUE THREAD

**Issue by gandras** [reformatus/enekeskonyv-app#54]
os: Android
app verzió: 3.0.6
A 48-as énekeskönyvbeli 68. zsoltár 17. versszaka hiányosnak tűnik, az enekeskonyv.jsonban [ez a sor](https://github.com/reformatus/enekeskonyv-app/blob/a9f9f06fc0cb1a91dc70a8c9156e91c1acc6cfee/assets/enekeskonyv.json#L1448) ellenőrizendő szerintem.
screenshot: ![Zs68vsz17](https://github.com/reformatus/enekeskonyv-app/assets/3263582/65ed9b1b-d871-4463-92ae-17cd63b73e7b)

**Comment by boobaa** [comment]
Ellenőriztem egy papír-alapú énekeskönyvben, és valóban így, csak 6 sornyi szöveggel szerepel a 68. zsoltár utolsó versszaka – tehát ez nem az app vagy az adatbázis „hibája”.

Hasonló figyelhető meg (többek között) a 32. és 54. zsoltároknál is (hogy csak két példát említsek). (Elképzelhető, hogy van erre a jelenségre szakkifejezés is, amit sajnos nem ismerek.)

Mindenesetre köszönjük az észrevételt! :)
