### ISSUE TITLE
Ugrás közvetlen versszakra

### ISSUE THREAD

**Issue by boobaa** [reformatus/enekeskonyv-app#8]
…az Ugrás énekre űrlapon.

(Mi legyen az elválasztó az énekszám és a versszakszám között? iOS-en például csak számok vannak a billentyűzeten minden egyéb jel nélkül; Androidon volna vessző, pont, kötőjel, szóköz, ha engedné a TextFormField.inputFormatters.)

**Comment by RedyAu** [comment]
Két külön field lenne célszerű imo. Androidon megjelenik egy tovább gomb a billentyűzeten, amivel átugrik a másikra, iOS-en pedig lehet tenni "kézzel" a billentyűzet fölé. #21
